import { computeStats, symbolInventory } from './stats.js';
import { CATEGORIES } from './symbols.js';
import { NOTE_CATS, ROUTE_KINDS } from './hidden.js';
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const f1 = n => n.toFixed(1);

export function buildCsv(project) {
  const rows = symbolInventory(project);
  const head = ['Level', 'Room', 'Symbol (NL)', 'Symbol (EN)', 'Category', 'Circuit', 'Label', 'x (m)', 'y (m)', 'Height (m)'];
  const q = v => `"${String(v ?? '').replace(/"/g, '""')}"`;
  return '﻿' + [head.map(q).join(';'), ...rows.map(r => [r.level, r.room, r.nl, r.en, (CATEGORIES[r.cat] || {}).en || r.cat, r.circuit, r.label, r.x.toFixed(2), r.y.toFixed(2), r.z.toFixed(2)].map(q).join(';'))].join('\n');
}

export function buildReport(project) {
  const st = computeStats(project), inv = symbolInventory(project);
  const types = new Map(); for (const r of inv) { const k = r.nl; const o = types.get(k) || { nl: r.nl, en: r.en, cat: r.cat, n: 0, per: {} }; o.n++; o.per[r.level] = (o.per[r.level] || 0) + 1; types.set(k, o); }
  const circ = new Map(); for (const r of inv) { const k = r.circuit || '—'; const o = circ.get(k) || { n: 0, rooms: new Set(), items: {} }; o.n++; if (r.room) o.rooms.add(r.room); o.items[r.nl] = (o.items[r.nl] || 0) + 1; circ.set(k, o); }
  const lv = st.levels;
  const warn = []; for (const l of project.levels) { const u = l.underlays.plan; if (u && !u.calibrated) warn.push(`${l.name}: scale not verified`); }
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${esc(project.name)} – house report</title><style>
body{font:14px/1.5 system-ui,Segoe UI,Roboto,sans-serif;color:#1b2536;max-width:900px;margin:30px auto;padding:0 20px}h1{margin-bottom:0}h2{margin-top:34px;border-bottom:2px solid #2563eb;padding-bottom:4px}
table{border-collapse:collapse;width:100%;margin:10px 0}th,td{border-bottom:1px solid #d6dbe5;padding:5px 8px;text-align:left}th{background:#eef2fa;font-size:12px;text-transform:uppercase;letter-spacing:.4px}td.n,th.n{text-align:right}.k{display:flex;gap:14px;flex-wrap:wrap}.k div{background:#eef2fa;border-radius:8px;padding:10px 16px}.k b{display:block;font-size:20px}.warn{color:#b45309}@media print{h2{break-after:avoid}}
</style></head><body>
<h1>${esc(project.name)}</h1><div>House report · ${new Date().toLocaleDateString()} · generated by HouseVault</div>
<h2>Overview</h2><div class="k"><div><b>${f1(st.gfa)} m²</b>floor area (enclosed rooms)</div><div><b>${f1(st.volume)} m³</b>volume</div><div><b>${lv.length}</b>levels</div><div><b>${st.rooms}</b>rooms</div><div><b>${st.windows}</b>windows</div><div><b>${st.doors}</b>doors / openings</div><div><b>${st.symbols}</b>electrical symbols</div></div>
${warn.length ? `<p class="warn">⚠ ${warn.map(esc).join(' · ')}</p>` : ''}
<h2>Levels and rooms</h2>${lv.map(l => `<h3>${esc(l.name)} – ${f1(l.area)} m², ceiling height ${l.height} m</h3><table><tr><th>Room</th><th class="n">Area m²</th><th class="n">Window area m²</th><th class="n">Daylight (window/floor)</th></tr>${l.rooms.map(r => `<tr><td>${esc(r.name)}</td><td class="n">${f1(r.area)}</td><td class="n">${f1(r.windowArea)}</td><td class="n">${r.windowArea ? Math.round(r.daylight * 100) + ' %' : '–'}</td></tr>`).join('') || '<tr><td colspan="4">No closed rooms detected</td></tr>'}</table>`).join('')}
<h2>Electrical installation</h2><table><tr><th>Symbol</th><th>English</th>${lv.map(l => `<th class="n">${esc(l.name)}</th>`).join('')}<th class="n">Total</th></tr>${[...types.values()].sort((a, b) => b.n - a.n).map(t => `<tr><td>${esc(t.nl)}</td><td>${esc(t.en)}</td>${lv.map(l => `<td class="n">${t.per[l.name] || ''}</td>`).join('')}<td class="n"><b>${t.n}</b></td></tr>`).join('') || '<tr><td colspan="9">No symbols placed yet</td></tr>'}</table>
<h2>Circuits (breakers)</h2><table><tr><th>Circuit</th><th>Name</th><th class="n">Devices</th><th>Rooms</th><th>What</th></tr>${[...circ.entries()].sort().map(([c, o]) => `<tr><td>${esc(c)}</td><td>${esc((project.circuitNames || {})[c] || '')}</td><td class="n">${o.n}</td><td>${esc([...o.rooms].join(', '))}</td><td>${esc(Object.entries(o.items).map(([k, n]) => n + '× ' + k).join(', '))}</td></tr>`).join('') || '<tr><td colspan="5">No circuits assigned</td></tr>'}</table>
${inv.length ? `<h2>Device list</h2><table><tr><th>Name</th><th>Type</th><th>Room</th><th>Level</th><th>Circuit</th></tr>${inv.slice(0, 500).map(r => `<tr><td>${esc(r.label || '–')}</td><td>${esc(r.nl)}</td><td>${esc(r.room)}</td><td>${esc(r.level)}</td><td>${esc(r.circuit)}</td></tr>`).join('')}</table>` : ''}
${project.levels.some(l => (l.notes || []).length || (l.routes || []).length) ? `<h2>Hidden installations &amp; notes</h2><table><tr><th>Level</th><th>Kind</th><th>Note</th></tr>${project.levels.flatMap(l => [...(l.notes || []).map(n => `<tr><td>${esc(l.name)}</td><td>${esc((NOTE_CATS[n.cat] || NOTE_CATS.other).label)}</td><td>${esc(n.text)}</td></tr>`), ...(l.routes || []).map(r => `<tr><td>${esc(l.name)}</td><td>${esc(ROUTE_KINDS[r.kind].label)}</td><td>${esc(r.label || '')} (${r.pts.reduce((a, p, i, arr) => i ? a + Math.hypot(p[0] - arr[i - 1][0], p[1] - arr[i - 1][1]) : 0, 0).toFixed(1)} m at ${r.z} m)</td></tr>`)]).join('')}</table>` : ''}
<p style="color:#6b7280;margin-top:30px">Areas are derived from the traced walls, so they are only as accurate as the plan scale. Not an official measurement or compliance document.</p>
</body></html>`;
}
