// Single source of truth for the version: package.json → js/version.js (shown in the app) 
const fs = require('fs'), path = require('path');
const pkg = require('../package.json');
fs.writeFileSync(path.join(__dirname, '..', 'js', 'version.js'), `// generated by scripts/sync-version.js – do not edit\nexport const VERSION = '${pkg.version}';\n`);
console.log('version.js ->', pkg.version);
